// generated by tooling/generate.mjs from tokens.json — do not edit
export type SchemeName = 'dark' | 'light' | 'oled';
export type ThemeName = SchemeName | 'system';

export const schemes = {
  dark: {
    canvas: '#1a1b26',
    stage: '#13141c',
    deep: '#0e0e14',
    raised: '#24283b',
    textPrimary: '#a9b1d6',
    textBright: '#c0caf5',
    textSecondary: '#828ab3',
    divider: '#414868',
    accent: '#7aa2f7',
    accentSoft: 'rgba(122,162,247,0.15)',
    warn: '#e0af68',
    liked: '#f7768e',
    fg08: 'rgba(169,177,214,0.07)',
    fg18: 'rgba(169,177,214,0.16)',
    fg25: 'rgba(169,177,214,0.25)',
    fg40: 'rgba(169,177,214,0.40)',
    glass: 'rgba(20,21,29,0.55)',
    hairline: 'rgba(169,177,214,0.12)',
  },
  light: {
    canvas: '#f5f6fa',
    stage: '#eceef4',
    deep: '#dfe2ec',
    raised: '#ffffff',
    textPrimary: '#343a52',
    textBright: '#222840',
    textSecondary: '#575d85',
    divider: '#c4c8d8',
    accent: '#1a5ac8',
    accentSoft: 'rgba(26,90,200,0.14)',
    warn: '#8a6524',
    liked: '#b24a60',
    fg08: 'rgba(52,58,82,0.05)',
    fg18: 'rgba(52,58,82,0.12)',
    fg25: 'rgba(52,58,82,0.24)',
    fg40: 'rgba(52,58,82,0.40)',
    glass: 'rgba(255,255,255,0.55)',
    hairline: 'rgba(52,58,82,0.12)',
  },
  oled: {
    canvas: '#000000',
    stage: '#06060a',
    deep: '#000000',
    raised: '#12131a',
    textPrimary: '#a9b1d6',
    textBright: '#c0caf5',
    textSecondary: '#828ab3',
    divider: '#23253a',
    accent: '#7aa2f7',
    accentSoft: 'rgba(122,162,247,0.15)',
    warn: '#e0af68',
    liked: '#f7768e',
    fg08: 'rgba(169,177,214,0.07)',
    fg18: 'rgba(169,177,214,0.16)',
    fg25: 'rgba(169,177,214,0.25)',
    fg40: 'rgba(169,177,214,0.40)',
    glass: 'rgba(14,15,22,0.60)',
    hairline: 'rgba(169,177,214,0.11)',
  },
} as const;

export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  display: 48,
} as const;

export const radius = {
  frame: 0,
  control: 6,
  float: 12,
  thumb: 5,
  pill: 999,
} as const;

export const sizes = {
  trackRow: 50,
  touch: 44,
  navbarAndroid: 72,
  navbarIos: 58,
  miniPlayer: 52,
  artworkRing: 48,
} as const;

export const strokes = {
  hairline: 1,
  progress: 2,
  progressAndroid: 2.5,
} as const;

export const fontFamilies = {
  regular: 'JetBrainsMono_400Regular',
  medium: 'JetBrainsMono_500Medium',
  bold: 'JetBrainsMono_700Bold',
} as const;

export const typography = {
  display: { fontSize: 20, lineHeight: 24, fontFamily: 'JetBrainsMono_700Bold' },
  title: { fontSize: 16, lineHeight: 20, fontFamily: 'JetBrainsMono_700Bold' },
  heading: { fontSize: 13, lineHeight: 17, fontFamily: 'JetBrainsMono_700Bold' },
  body: { fontSize: 12, lineHeight: 17, fontFamily: 'JetBrainsMono_500Medium' },
  metadata: { fontSize: 10, lineHeight: 14, fontFamily: 'JetBrainsMono_400Regular' },
  label: { fontSize: 10, lineHeight: 14, fontFamily: 'JetBrainsMono_700Bold', letterSpacing: 1.2 },
} as const;

export const motion = {
  press: 120,
  state: 180,
  sheet: 300,
  spring: { duration: 400, dampingRatio: 1 },
  gesture: { duration: 300, dampingRatio: 0.8 },
} as const;

export function resolveTheme(
  theme: ThemeName,
  system: 'light' | 'dark',
): SchemeName {
  return theme === 'system' ? system : theme;
}
