// generated by tooling/generate.mjs from tokens.json — do not edit
export type SchemeName = 'dark' | 'light' | 'oled';
export type ThemeName = SchemeName | 'system' | 'adaptive';

export const schemes = {
  dark: {
    canvas: '#161512',
    stage: '#100e0c',
    deep: '#0b0a09',
    raised: '#232019',
    textPrimary: '#e6e1d8',
    textBright: '#f5f1e9',
    textSecondary: '#a8a094',
    divider: '#3a352d',
    accent: '#ff8a3d',
    accentSoft: 'rgba(255,138,61,0.16)',
    warn: '#ff8787',
    liked: '#f97b9b',
    fg08: 'rgba(230,225,216,0.08)',
    fg18: 'rgba(230,225,216,0.16)',
    fg25: 'rgba(230,225,216,0.26)',
    fg40: 'rgba(230,225,216,0.42)',
    glass: 'rgba(15,14,12,0.55)',
    glassControl: 'rgba(255,255,255,0.12)',
    scrim: 'rgba(0,0,0,0.50)',
    hairline: 'rgba(230,225,216,0.14)',
    thumb: '#ffffff',
  },
  light: {
    canvas: '#faf8f3',
    stage: '#f1ede5',
    deep: '#e7e1d4',
    raised: '#ffffff',
    textPrimary: '#2a251f',
    textBright: '#171310',
    textSecondary: '#6f6659',
    divider: '#d8d1c2',
    accent: '#c2410c',
    accentSoft: 'rgba(194,65,12,0.11)',
    warn: '#a61e1e',
    liked: '#b0214f',
    fg08: 'rgba(42,37,31,0.06)',
    fg18: 'rgba(42,37,31,0.13)',
    fg25: 'rgba(42,37,31,0.26)',
    fg40: 'rgba(42,37,31,0.42)',
    glass: 'rgba(255,255,255,0.60)',
    glassControl: 'rgba(255,255,255,0.12)',
    scrim: 'rgba(31,26,20,0.35)',
    hairline: 'rgba(42,37,31,0.15)',
    thumb: '#ffffff',
  },
  oled: {
    canvas: '#000000',
    stage: '#070605',
    deep: '#000000',
    raised: '#16140f',
    textPrimary: '#e6e1d8',
    textBright: '#f5f1e9',
    textSecondary: '#a8a094',
    divider: '#29241e',
    accent: '#ff8a3d',
    accentSoft: 'rgba(255,138,61,0.18)',
    warn: '#ff8787',
    liked: '#f97b9b',
    fg08: 'rgba(230,225,216,0.08)',
    fg18: 'rgba(230,225,216,0.16)',
    fg25: 'rgba(230,225,216,0.26)',
    fg40: 'rgba(230,225,216,0.42)',
    glass: 'rgba(4,4,3,0.60)',
    glassControl: 'rgba(255,255,255,0.12)',
    scrim: 'rgba(0,0,0,0.55)',
    hairline: 'rgba(230,225,216,0.13)',
    thumb: '#ffffff',
  },
} as const;

export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  screen: 14,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  display: 48,
} as const;

export const radius = {
  frame: 0,
  control: 8,
  float: 16,
  thumb: 5,
  pill: 999,
} as const;

export const sizes = {
  trackRow: 50,
  touch: 44,
  navbarAndroid: 72,
  navbarIos: 58,
  miniPlayer: 52,
  artworkRing: 48,
} as const;

export const strokes = {
  hairline: 1,
  progress: 2,
  progressAndroid: 2.5,
} as const;

export const fontFamilies = {
  regular: 'Inter_400Regular',
  medium: 'Inter_500Medium',
  bold: 'Inter_700Bold',
} as const;

export const typography = {
  display: { fontSize: 20, lineHeight: 24, fontFamily: 'Inter_700Bold' },
  title: { fontSize: 16, lineHeight: 20, fontFamily: 'Inter_700Bold' },
  heading: { fontSize: 13, lineHeight: 17, fontFamily: 'Inter_700Bold' },
  body: { fontSize: 12, lineHeight: 17, fontFamily: 'Inter_500Medium' },
  metadata: { fontSize: 10, lineHeight: 14, fontFamily: 'Inter_400Regular' },
  label: { fontSize: 10, lineHeight: 14, fontFamily: 'Inter_700Bold', letterSpacing: 1.2 },
} as const;

export const motion = {
  press: 120,
  state: 180,
  sheet: 300,
  spring: { duration: 400, dampingRatio: 1 },
  gesture: { duration: 300, dampingRatio: 0.8 },
} as const;

/**
 * Resolves a ThemeName to a concrete scheme. 'adaptive' without a
 * derived scheme is the honest fallback — it resolves like 'system'
 * (packages/design-tokens/src/adaptive.ts owns palette derivation).
 */
export function resolveTheme(
  theme: ThemeName,
  system: 'light' | 'dark',
  adaptiveScheme?: 'light' | 'dark',
): SchemeName {
  if (theme === 'adaptive') {
    return adaptiveScheme ?? system;
  }
  return theme === 'system' ? system : theme;
}
