// Generates src/tokens.ts and dist/tokens.css from tokens.json.
// The DTCG source is the only authority — the outputs are checked in.
// Imported by tooling/test.mjs; writes only when run as a script.
import {
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';

const HEADER_TS =
  '// generated by tooling/generate.mjs from tokens.json — do not edit\n';
const HEADER_CSS =
  '/* generated by tooling/generate.mjs from tokens.json — do not edit */\n';

const kebab = (name) =>
  name.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`);
const leaf = (node) => node['$value'];
const px = (n) => `${n}px`;
const ms = (n) => `${n}ms`;

function flatTokens(group) {
  // { name: value } from a flat DTCG group, preserving source order.
  return Object.fromEntries(
    Object.entries(group).map(([name, node]) => [name, leaf(node)]),
  );
}

function tsObject(name, entries) {
  const lines = Object.entries(entries).map(
    ([key, value]) =>
      `  ${key}: ${typeof value === 'string' ? `'${value}'` : value},`,
  );
  return `export const ${name} = {\n${lines.join('\n')}\n} as const;\n`;
}

export function renderTokens(source) {
  const schemeNames = Object.keys(source['schemes']);
  const families = flatTokens(source['typography']['families']);

  // ---------- TypeScript ----------
  let ts = HEADER_TS;
  ts += `export type SchemeName = ${schemeNames
    .map((n) => `'${n}'`)
    .join(' | ')};\n`;
  ts += `export type ThemeName = SchemeName | 'system';\n\n`;

  ts += 'export const schemes = {\n';
  for (const [scheme, roles] of Object.entries(source['schemes'])) {
    ts += `  ${scheme}: {\n`;
    for (const [role, node] of Object.entries(roles)) {
      ts += `    ${role}: '${leaf(node)}',\n`;
    }
    ts += '  },\n';
  }
  ts += '} as const;\n\n';

  ts += tsObject('spacing', flatTokens(source['spacing']));
  ts += '\n';
  ts += tsObject('radius', flatTokens(source['radius']));
  ts += '\n';
  ts += tsObject('sizes', flatTokens(source['sizes']));
  ts += '\n';
  ts += tsObject('strokes', flatTokens(source['strokes']));
  ts += '\n';
  ts += tsObject('fontFamilies', families);
  ts += '\n';

  ts += 'export const typography = {\n';
  for (const [styleName, style] of Object.entries(
    source['typography']['styles'],
  )) {
    const familyKey = leaf(style['fontFamily']);
    const family = families[familyKey];
    if (family === undefined) {
      throw new Error(
        `typography.${styleName}.fontFamily references unknown family '${familyKey}'`,
      );
    }
    const parts = [
      `fontSize: ${leaf(style['fontSize'])}`,
      `lineHeight: ${leaf(style['lineHeight'])}`,
      `fontFamily: '${family}'`,
    ];
    if (style['letterSpacing'] !== undefined) {
      parts.push(`letterSpacing: ${leaf(style['letterSpacing'])}`);
    }
    ts += `  ${styleName}: { ${parts.join(', ')} },\n`;
  }
  ts += '} as const;\n\n';

  ts += 'export const motion = {\n';
  for (const [name, node] of Object.entries(source['motion'])) {
    if ('$value' in node) {
      ts += `  ${name}: ${leaf(node)},\n`;
    } else {
      const inner = Object.entries(node)
        .map(([k, v]) => `${k}: ${leaf(v)}`)
        .join(', ');
      ts += `  ${name}: { ${inner} },\n`;
    }
  }
  ts += '} as const;\n\n';

  ts += `export function resolveTheme(
  theme: ThemeName,
  system: 'light' | 'dark',
): SchemeName {
  return theme === 'system' ? system : theme;
}
`;

  // ---------- CSS ----------
  const roleVars = (roles) =>
    Object.entries(roles)
      .map(([role, node]) => `  --${kebab(role)}: ${leaf(node)};`)
      .join('\n');

  const [rootScheme, ...restSchemes] = schemeNames;
  let css = HEADER_CSS;
  css += ':root,\n';
  css += `.t-${rootScheme} {\n`;
  css += `${roleVars(source['schemes'][rootScheme])}\n`;
  for (const [name, node] of Object.entries(source['spacing'])) {
    css += `  --spacing-${kebab(name)}: ${px(leaf(node))};\n`;
  }
  for (const [name, node] of Object.entries(source['radius'])) {
    css += `  --radius-${kebab(name)}: ${px(leaf(node))};\n`;
  }
  for (const [name, node] of Object.entries(source['sizes'])) {
    css += `  --size-${kebab(name)}: ${px(leaf(node))};\n`;
  }
  for (const [name, node] of Object.entries(source['strokes'])) {
    css += `  --stroke-${kebab(name)}: ${px(leaf(node))};\n`;
  }
  for (const [name, node] of Object.entries(
    source['typography']['families'],
  )) {
    css += `  --font-${kebab(name)}: ${leaf(node)};\n`;
  }
  for (const [styleName, style] of Object.entries(
    source['typography']['styles'],
  )) {
    const family = families[leaf(style['fontFamily'])];
    css += `  --font-${kebab(styleName)}: ${px(leaf(style['fontSize']))};\n`;
    css += `  --font-${kebab(styleName)}-line: ${px(leaf(style['lineHeight']))};\n`;
    css += `  --font-${kebab(styleName)}-family: ${family};\n`;
    if (style['letterSpacing'] !== undefined) {
      css += `  --font-${kebab(styleName)}-tracking: ${leaf(style['letterSpacing'])};\n`;
    }
  }
  for (const [name, node] of Object.entries(source['motion'])) {
    if ('$value' in node) {
      css += `  --motion-${kebab(name)}: ${ms(leaf(node))};\n`;
    } else {
      for (const [sub, subNode] of Object.entries(node)) {
        css += `  --${kebab(name)}-${kebab(sub)}: ${sub === 'duration' ? ms(leaf(subNode)) : leaf(subNode)};\n`;
      }
    }
  }
  css += '}\n';
  for (const scheme of restSchemes) {
    css += `.t-${scheme} {\n`;
    css += `${roleVars(source['schemes'][scheme])}\n`;
    css += '}\n';
  }

  return { ts, css };
}

const invoked =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];

if (invoked) {
  const root = new URL('..', import.meta.url);
  const source = JSON.parse(
    readFileSync(new URL('tokens.json', root), 'utf8'),
  );
  const { ts, css } = renderTokens(source);
  mkdirSync(new URL('src', root), { recursive: true });
  mkdirSync(new URL('dist', root), { recursive: true });
  writeFileSync(new URL('src/tokens.ts', root), ts);
  writeFileSync(new URL('dist/tokens.css', root), css);
  console.log('generated src/tokens.ts and dist/tokens.css');
}
