/** Every renderer↔main channel name, in one map. */

export const CHANNELS = {
  appMeta: 'app:meta',
  dialogPickFolder: 'dialog:pickFolder',
  dialogPickFiles: 'dialog:pickFiles',
  netSnapshot: 'net:snapshot',
  netEvents: 'net:events',
  netSubscribe: 'net:subscribe',
  netUnsubscribe: 'net:unsubscribe',
  secureGet: 'secure:get',
  secureSet: 'secure:set',
  secureDelete: 'secure:delete',
  storageBegin: 'storage:begin',
  storageCommit: 'storage:commit',
  storageRollback: 'storage:rollback',
  storageCancel: 'storage:cancel',
  storageExecute: 'storage:execute',
  storageQuery: 'storage:query',
  storageBackup: 'storage:backup',
  storageDropBackup: 'storage:dropBackup',
  utilityPing: 'utility:ping',
  hostPlugins: 'host:plugins',
  hostRequest: 'host:request',
  hostCancel: 'host:cancel',
  streamPrepare: 'stream:prepare',
  streamDevPrepare: 'stream:dev-prepare',
  streamServeUrl: 'stream:serve-url',
  streamOpen: 'stream:open',
  streamRead: 'stream:read',
  streamClose: 'stream:close',
  streamRelease: 'stream:release',
  streamMarks: 'stream:marks',
  streamCancel: 'stream:cancel',
  streamPort: 'stream:port',
  /** Main→renderer port delivery — carries the pump's MessagePort. */
  streamBytes: 'stream-bytes',
  syncStatus: 'sync:status',
  syncPairing: 'sync:pairing',
  syncDevices: 'sync:devices',
  syncUnpair: 'sync:unpair',
  syncDeltas: 'sync:deltas',
  syncImportDelta: 'sync:importDelta',
  syncTrigger: 'sync:trigger',
  syncLocalChanges: 'sync:localChanges',
  transferEnsureDir: 'transfer:ensureDir',
  transferBegin: 'transfer:begin',
  transferWrite: 'transfer:write',
  transferCommit: 'transfer:commit',
  transferFinalize: 'transfer:finalize',
  transferAbort: 'transfer:abort',
  transferStat: 'transfer:stat',
  transferRemove: 'transfer:remove',
  transferSweepPartials: 'transfer:sweepPartials',
  transferList: 'transfer:list',
  transferStatus: 'transfer:status',
  transferStats: 'transfer:stats',
  tagreadEnumerate: 'tagread:enumerate',
  tagreadFingerprint: 'tagread:fingerprint',
  tagreadRead: 'tagread:read',
  localAdd: 'local:add',
  localProbe: 'local:probe',
  localList: 'local:list',
  localPlayback: 'local:playback',
  localSweep: 'local:sweep',
} as const;

export type ChannelName = (typeof CHANNELS)[keyof typeof CHANNELS];
