import { run as runEnvelope } from './utility/envelope.test.ts';
import { run as runRouter } from './utility/router.test.ts';
import { run as runHost } from './utility/host.test.ts';
import { run as runUtilityStorage } from './utility/storage.test.ts';
import { run as runStream } from './utility/stream.test.ts';
import { run as runSupervisor } from './main/supervisor.test.ts';
import { run as runIpc } from './main/ipc.test.ts';
import { run as runWindowState } from './main/window-state.test.ts';
import { run as runSecureStore } from './main/secure-store.test.ts';
import { run as runNetMonitor } from './main/net-monitor.test.ts';
import { run as runContract } from './shared/contract.test.ts';
import { run as runPumpProtocol } from './shared/pump-protocol.test.ts';
import { run as runBytes } from './utility/bytes.test.ts';
import { run as runSqliteDriver } from './renderer/sqlite-driver.test.ts';
import { run as runContainers } from './renderer/containers.test.ts';
import { run as runMseSource } from './renderer/mse-source.test.ts';
import { run as runWebPlayer } from './renderer/web-player.test.ts';

runEnvelope();
await runRouter();
await runHost();
await runUtilityStorage();
await runStream();
await runSupervisor();
await runIpc();
await runWindowState();
await runSecureStore();
await runNetMonitor();
runContract();
runPumpProtocol();
await runBytes();
await runSqliteDriver();
runContainers();
await runMseSource();
await runWebPlayer();
console.log('desktop shell tests passed');
