import { run as runEnvelope } from './utility/envelope.test.ts';
import { run as runRouter } from './utility/router.test.ts';
import { run as runHost } from './utility/host.test.ts';
import { run as runUtilityStorage } from './utility/storage.test.ts';
import { run as runStream } from './utility/stream.test.ts';
import { run as runSupervisor } from './main/supervisor.test.ts';
import { run as runIpc } from './main/ipc.test.ts';
import { run as runWindowState } from './main/window-state.test.ts';
import { run as runSecureStore } from './main/secure-store.test.ts';
import { run as runNetMonitor } from './main/net-monitor.test.ts';
import { run as runSyncKeys } from './main/sync-keys.test.ts';
import { run as runService } from './utility/service.test.ts';
import { run as runSyncWire } from './utility/sync-wire.test.ts';
import { run as runSyncCrypto } from './utility/sync-crypto.test.ts';
import { run as runSyncServer } from './utility/sync-server.test.ts';
import { run as runSyncLog } from './utility/sync-log.test.ts';
import { run as runSyncEngine } from './utility/sync-engine.test.ts';
import { run as runContract } from './shared/contract.test.ts';
import { run as runPumpProtocol } from './shared/pump-protocol.test.ts';
import { run as runBytes } from './utility/bytes.test.ts';
import { run as runSqliteDriver } from './renderer/sqlite-driver.test.ts';
import { run as runContainers } from './renderer/containers.test.ts';
import { run as runMseSource } from './renderer/mse-source.test.ts';
import { run as runWebPlayer } from './renderer/web-player.test.ts';
import { run as runTransfer } from './utility/transfer.test.ts';
import { run as runTags } from './utility/tags.test.ts';
import { run as runLocal } from './utility/local.test.ts';
import { run as runLocalPaths } from './shared/local-paths.test.ts';
import { run as runTagReader } from './renderer/tag-reader.test.ts';
import { run as runTransferPort } from './renderer/transfer-port.test.ts';
import { run as runLocalPlayback } from './renderer/local-playback.test.ts';
import { run as runProvider } from './renderer/provider.test.ts';
import { run as runController } from './renderer/controller.test.ts';

runEnvelope();
await runRouter();
await runHost();
await runUtilityStorage();
await runStream();
await runSupervisor();
await runIpc();
await runWindowState();
await runSecureStore();
await runNetMonitor();
await runSyncKeys();
await runService();
await runSyncWire();
await runSyncCrypto();
await runSyncServer();
await runSyncLog();
await runSyncEngine();
runContract();
runPumpProtocol();
await runBytes();
await runSqliteDriver();
runContainers();
await runMseSource();
await runWebPlayer();
await runTransfer();
await runTags();
await runLocal();
runLocalPaths();
await runTagReader();
await runTransferPort();
runLocalPlayback();
await runProvider();
await runController();
console.log('desktop shell tests passed');
