// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(auqw_mobile_bindingsFFI)
import auqw_mobile_bindingsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_auqw_mobile_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_auqw_mobile_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAuqwMobileBindingsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The plugin host object: owns a tokio runtime, an HTTP client, the
 * loaded plugin set, and per-request cancellation tokens.
 */
public protocol PluginHostProtocol: AnyObject, Sendable {
    
    /**
     * Cancel an in-flight request; unknown ids are a no-op. A
     * `cancelPrepare` landing after `prepared` also abandons the
     * produced session — but only while it is still unattached: a
     * playing consumer is never cancelled out from under playback.
     */
    func cancel(requestId: String) 
    
    /**
     * Validate and register a plugin artifact. Returns the manifest id.
     *
     * # Errors
     * [`HostError::Load`] on any contract or policy violation.
     */
    func loadPlugin(wasm: Data, manifestJson: String) throws  -> String
    
    /**
     * Run the spin conformance guest to measure the fuel trap latency
     * on-device. Blocks the calling thread on the runtime.
     *
     * # Errors
     * [`HostError::Load`] if the artifact fails validation.
     */
    func runSpin(wasm: Data, manifestJson: String) throws  -> SpinReport
    
    /**
     * Start any declared capability with a JSON object payload. The
     * outcome carries the raw `done.result` JSON.
     *
     * # Errors
     * [`HostError::Runtime`] when `payload_json` is not a JSON object;
     * [`HostError::UnknownPlugin`] for an unloaded `plugin_id`.
     */
    func startRequest(pluginId: String, capability: String, payloadJson: String, listener: RequestListener) throws  -> String
    
    /**
     * Start a `playback.resolve` invocation on the runtime. The
     * returned request id is passed back through the listener.
     *
     * # Errors
     * [`HostError::UnknownPlugin`] if `plugin_id` was never loaded.
     */
    func startResolve(pluginId: String, sourceRef: String, listener: ResolveListener) throws  -> String
    
    /**
     * Resolve `source_ref` and register the result as a prepared
     * stream session (bounded speculative head fill). The outcome —
     * including the opaque stream handle — arrives on `listener`.
     *
     * # Errors
     * [`HostError::UnknownPlugin`] if `plugin_id` was never loaded;
     * [`HostError::Runtime`] when the seam is not configured.
     */
    func startPrepare(pluginId: String, sourceRef: String, listener: PrepareListener) throws  -> String
    
    /**
     * DataSource close: detaches the consumer; the session stays live
     * for re-attach.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] for an unknown handle.
     */
    func streamClose(handle: String) throws 
    
    /**
     * Attach a consumer at `position` (DataSource open). Returns
     * `content_length - position` when the stream total is known.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] with the session's kind otherwise.
     */
    func streamOpen(handle: String, position: UInt64) throws  -> UInt64?
    
    /**
     * The session's lifecycle marks — available even after terminal
     * states.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] for an unknown handle.
     */
    func streamPhaseMarks(handle: String) throws  -> StreamPhaseMarks
    
    /**
     * Blocking read — **foreign (JNI/DataSource) threads only**;
     * parking a runtime worker is a bug. Empty bytes = EOF. Bounded by
     * the seam's read deadline; terminal transitions wake into their
     * typed error.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] with the session's kind otherwise.
     */
    func streamRead(handle: String, position: UInt64, maxLen: UInt64) throws  -> Data
    
    /**
     * Terminal release: parked readers unwind `released`, in-flight
     * work aborts, the partial file is evicted. Idempotent.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured.
     */
    func streamRelease(handle: String) throws 
    
}
/**
 * The plugin host object: owns a tokio runtime, an HTTP client, the
 * loaded plugin set, and per-request cancellation tokens.
 */
open class PluginHost: PluginHostProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_auqw_mobile_bindings_fn_clone_pluginhost(self.handle, $0) }
    }
    /**
     * Create a host with a two-worker tokio runtime.
     *
     * # Errors
     * [`HostError::Runtime`] if the runtime or TLS backend cannot start.
     */
public convenience init(config: HostConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeHostError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_constructor_pluginhost_new(
        FfiConverterTypeHostConfig_lower(config),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_auqw_mobile_bindings_fn_free_pluginhost(handle, $0) }
    }

    

    
    /**
     * Cancel an in-flight request; unknown ids are a no-op. A
     * `cancelPrepare` landing after `prepared` also abandons the
     * produced session — but only while it is still unattached: a
     * playing consumer is never cancelled out from under playback.
     */
open func cancel(requestId: String)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_cancel(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(requestId),uniffiCallStatus
    )
}
}
    
    /**
     * Validate and register a plugin artifact. Returns the manifest id.
     *
     * # Errors
     * [`HostError::Load`] on any contract or policy violation.
     */
open func loadPlugin(wasm: Data, manifestJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHostError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_load_plugin(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(wasm),
        FfiConverterString.lower(manifestJson),uniffiCallStatus
    )
})
}
    
    /**
     * Run the spin conformance guest to measure the fuel trap latency
     * on-device. Blocks the calling thread on the runtime.
     *
     * # Errors
     * [`HostError::Load`] if the artifact fails validation.
     */
open func runSpin(wasm: Data, manifestJson: String)throws  -> SpinReport  {
    return try  FfiConverterTypeSpinReport_lift(try rustCallWithError(FfiConverterTypeHostError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_run_spin(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(wasm),
        FfiConverterString.lower(manifestJson),uniffiCallStatus
    )
})
}
    
    /**
     * Start any declared capability with a JSON object payload. The
     * outcome carries the raw `done.result` JSON.
     *
     * # Errors
     * [`HostError::Runtime`] when `payload_json` is not a JSON object;
     * [`HostError::UnknownPlugin`] for an unloaded `plugin_id`.
     */
open func startRequest(pluginId: String, capability: String, payloadJson: String, listener: RequestListener)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHostError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_start_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(pluginId),
        FfiConverterString.lower(capability),
        FfiConverterString.lower(payloadJson),
        FfiConverterCallbackInterfaceRequestListener_lower(listener),uniffiCallStatus
    )
})
}
    
    /**
     * Start a `playback.resolve` invocation on the runtime. The
     * returned request id is passed back through the listener.
     *
     * # Errors
     * [`HostError::UnknownPlugin`] if `plugin_id` was never loaded.
     */
open func startResolve(pluginId: String, sourceRef: String, listener: ResolveListener)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHostError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_start_resolve(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(pluginId),
        FfiConverterString.lower(sourceRef),
        FfiConverterCallbackInterfaceResolveListener_lower(listener),uniffiCallStatus
    )
})
}
    
    /**
     * Resolve `source_ref` and register the result as a prepared
     * stream session (bounded speculative head fill). The outcome —
     * including the opaque stream handle — arrives on `listener`.
     *
     * # Errors
     * [`HostError::UnknownPlugin`] if `plugin_id` was never loaded;
     * [`HostError::Runtime`] when the seam is not configured.
     */
open func startPrepare(pluginId: String, sourceRef: String, listener: PrepareListener)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHostError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_start_prepare(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(pluginId),
        FfiConverterString.lower(sourceRef),
        FfiConverterCallbackInterfacePrepareListener_lower(listener),uniffiCallStatus
    )
})
}
    
    /**
     * DataSource close: detaches the consumer; the session stays live
     * for re-attach.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] for an unknown handle.
     */
open func streamClose(handle: String)throws   {try rustCallWithError(FfiConverterTypeStreamError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_stream_close(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),uniffiCallStatus
    )
}
}
    
    /**
     * Attach a consumer at `position` (DataSource open). Returns
     * `content_length - position` when the stream total is known.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] with the session's kind otherwise.
     */
open func streamOpen(handle: String, position: UInt64)throws  -> UInt64?  {
    return try  FfiConverterOptionUInt64.lift(try rustCallWithError(FfiConverterTypeStreamError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_stream_open(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),
        FfiConverterUInt64.lower(position),uniffiCallStatus
    )
})
}
    
    /**
     * The session's lifecycle marks — available even after terminal
     * states.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] for an unknown handle.
     */
open func streamPhaseMarks(handle: String)throws  -> StreamPhaseMarks  {
    return try  FfiConverterTypeStreamPhaseMarks_lift(try rustCallWithError(FfiConverterTypeStreamError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_stream_phase_marks(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),uniffiCallStatus
    )
})
}
    
    /**
     * Blocking read — **foreign (JNI/DataSource) threads only**;
     * parking a runtime worker is a bug. Empty bytes = EOF. Bounded by
     * the seam's read deadline; terminal transitions wake into their
     * typed error.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured;
     * [`StreamError::Failed`] with the session's kind otherwise.
     */
open func streamRead(handle: String, position: UInt64, maxLen: UInt64)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeStreamError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_stream_read(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),
        FfiConverterUInt64.lower(position),
        FfiConverterUInt64.lower(maxLen),uniffiCallStatus
    )
})
}
    
    /**
     * Terminal release: parked readers unwind `released`, in-flight
     * work aborts, the partial file is evicted. Idempotent.
     *
     * # Errors
     * [`StreamError::Unavailable`] when the seam is not configured.
     */
open func streamRelease(handle: String)throws   {try rustCallWithError(FfiConverterTypeStreamError_lift) {
        uniffiCallStatus in
    uniffi_auqw_mobile_bindings_fn_method_pluginhost_stream_release(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(handle),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePluginHost: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PluginHost

    public static func lift(_ handle: UInt64) throws -> PluginHost {
        return PluginHost(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PluginHost) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PluginHost {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PluginHost, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePluginHost_lift(_ handle: UInt64) throws -> PluginHost {
    return try FfiConverterTypePluginHost.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePluginHost_lower(_ value: PluginHost) -> UInt64 {
    return FfiConverterTypePluginHost.lower(value)
}




/**
 * Per-invocation accounting for diagnostics.
 */
public struct AttemptSummary: Equatable, Hashable {
    /**
     * Host-generated request id.
     */
    public var requestId: String
    /**
     * `handle` steps executed.
     */
    public var steps: UInt32
    /**
     * HTTP requests performed for the guest.
     */
    public var httpCalls: UInt32
    /**
     * HTTP bytes moved, in and out.
     */
    public var bytes: UInt64
    /**
     * Fuel consumed across all guest entries.
     */
    public var fuelUsed: UInt64
    /**
     * Wall-clock elapsed.
     */
    public var elapsedMs: UInt64
    /**
     * Sanitized HTTP trace entries.
     */
    public var httpTrace: [HttpTraceSummary]
    /**
     * Guest log entries.
     */
    public var guestLog: [GuestLogSummary]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Host-generated request id.
         */requestId: String, 
        /**
         * `handle` steps executed.
         */steps: UInt32, 
        /**
         * HTTP requests performed for the guest.
         */httpCalls: UInt32, 
        /**
         * HTTP bytes moved, in and out.
         */bytes: UInt64, 
        /**
         * Fuel consumed across all guest entries.
         */fuelUsed: UInt64, 
        /**
         * Wall-clock elapsed.
         */elapsedMs: UInt64, 
        /**
         * Sanitized HTTP trace entries.
         */httpTrace: [HttpTraceSummary], 
        /**
         * Guest log entries.
         */guestLog: [GuestLogSummary]) {
        self.requestId = requestId
        self.steps = steps
        self.httpCalls = httpCalls
        self.bytes = bytes
        self.fuelUsed = fuelUsed
        self.elapsedMs = elapsedMs
        self.httpTrace = httpTrace
        self.guestLog = guestLog
    }

    

    
}

#if compiler(>=6)
extension AttemptSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttemptSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AttemptSummary {
        return
            try AttemptSummary(
                requestId: FfiConverterString.read(from: &buf), 
                steps: FfiConverterUInt32.read(from: &buf), 
                httpCalls: FfiConverterUInt32.read(from: &buf), 
                bytes: FfiConverterUInt64.read(from: &buf), 
                fuelUsed: FfiConverterUInt64.read(from: &buf), 
                elapsedMs: FfiConverterUInt64.read(from: &buf), 
                httpTrace: FfiConverterSequenceTypeHttpTraceSummary.read(from: &buf), 
                guestLog: FfiConverterSequenceTypeGuestLogSummary.read(from: &buf)
        )
    }

    public static func write(_ value: AttemptSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.requestId, into: &buf)
        FfiConverterUInt32.write(value.steps, into: &buf)
        FfiConverterUInt32.write(value.httpCalls, into: &buf)
        FfiConverterUInt64.write(value.bytes, into: &buf)
        FfiConverterUInt64.write(value.fuelUsed, into: &buf)
        FfiConverterUInt64.write(value.elapsedMs, into: &buf)
        FfiConverterSequenceTypeHttpTraceSummary.write(value.httpTrace, into: &buf)
        FfiConverterSequenceTypeGuestLogSummary.write(value.guestLog, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttemptSummary_lift(_ buf: RustBuffer) throws -> AttemptSummary {
    return try FfiConverterTypeAttemptSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttemptSummary_lower(_ value: AttemptSummary) -> RustBuffer {
    return FfiConverterTypeAttemptSummary.lower(value)
}


/**
 * One guest `log` entry, already redacted by the host.
 */
public struct GuestLogSummary: Equatable, Hashable {
    /**
     * `debug` | `info` | `warn` | `error`.
     */
    public var level: String
    /**
     * Redacted message text.
     */
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `debug` | `info` | `warn` | `error`.
         */level: String, 
        /**
         * Redacted message text.
         */message: String) {
        self.level = level
        self.message = message
    }

    

    
}

#if compiler(>=6)
extension GuestLogSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGuestLogSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GuestLogSummary {
        return
            try GuestLogSummary(
                level: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GuestLogSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.level, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGuestLogSummary_lift(_ buf: RustBuffer) throws -> GuestLogSummary {
    return try FfiConverterTypeGuestLogSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGuestLogSummary_lower(_ value: GuestLogSummary) -> RustBuffer {
    return FfiConverterTypeGuestLogSummary.lower(value)
}


/**
 * Host-side budgets the app may tune; all other dimensions take
 * `Budgets::default()`.
 */
public struct HostConfig: Equatable, Hashable {
    /**
     * Fuel granted to each guest entry.
     */
    public var fuelPerEntry: UInt64
    /**
     * Total fuel across one invocation.
     */
    public var fuelTotal: UInt64
    /**
     * Base URL of a bgutil-compatible PO-token service
     * (`POST {provider}/get_pot`). `None` leaves resolves anonymous.
     */
    public var potProviderUrl: String?
    /**
     * Path of the on-disk KV store the native shell supplies;
     * `None` keeps plugin state volatile.
     */
    public var statePath: String?
    /**
     * Directory for the sparse stream cache; `None` disables the
     * streaming seam — every `stream_*` call then fails
     * [`StreamError::Unavailable`] and `start_prepare` fails
     * synchronously.
     */
    public var streamPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Fuel granted to each guest entry.
         */fuelPerEntry: UInt64, 
        /**
         * Total fuel across one invocation.
         */fuelTotal: UInt64, 
        /**
         * Base URL of a bgutil-compatible PO-token service
         * (`POST {provider}/get_pot`). `None` leaves resolves anonymous.
         */potProviderUrl: String?, 
        /**
         * Path of the on-disk KV store the native shell supplies;
         * `None` keeps plugin state volatile.
         */statePath: String?, 
        /**
         * Directory for the sparse stream cache; `None` disables the
         * streaming seam — every `stream_*` call then fails
         * [`StreamError::Unavailable`] and `start_prepare` fails
         * synchronously.
         */streamPath: String?) {
        self.fuelPerEntry = fuelPerEntry
        self.fuelTotal = fuelTotal
        self.potProviderUrl = potProviderUrl
        self.statePath = statePath
        self.streamPath = streamPath
    }

    

    
}

#if compiler(>=6)
extension HostConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostConfig {
        return
            try HostConfig(
                fuelPerEntry: FfiConverterUInt64.read(from: &buf), 
                fuelTotal: FfiConverterUInt64.read(from: &buf), 
                potProviderUrl: FfiConverterOptionString.read(from: &buf), 
                statePath: FfiConverterOptionString.read(from: &buf), 
                streamPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HostConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.fuelPerEntry, into: &buf)
        FfiConverterUInt64.write(value.fuelTotal, into: &buf)
        FfiConverterOptionString.write(value.potProviderUrl, into: &buf)
        FfiConverterOptionString.write(value.statePath, into: &buf)
        FfiConverterOptionString.write(value.streamPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostConfig_lift(_ buf: RustBuffer) throws -> HostConfig {
    return try FfiConverterTypeHostConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostConfig_lower(_ value: HostConfig) -> RustBuffer {
    return FfiConverterTypeHostConfig.lower(value)
}


/**
 * One HTTP call from the attempt trace. `url` is already stripped of
 * query and fragment by the host — the signed parameters never cross
 * this boundary.
 */
public struct HttpTraceSummary: Equatable, Hashable {
    /**
     * HTTP method.
     */
    public var method: String
    /**
     * URL without query or fragment.
     */
    public var url: String
    /**
     * Response status when one was received.
     */
    public var status: UInt16?
    /**
     * Body bytes received.
     */
    public var bytes: UInt64
    /**
     * Round-trip milliseconds.
     */
    public var elapsedMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * HTTP method.
         */method: String, 
        /**
         * URL without query or fragment.
         */url: String, 
        /**
         * Response status when one was received.
         */status: UInt16?, 
        /**
         * Body bytes received.
         */bytes: UInt64, 
        /**
         * Round-trip milliseconds.
         */elapsedMs: UInt64) {
        self.method = method
        self.url = url
        self.status = status
        self.bytes = bytes
        self.elapsedMs = elapsedMs
    }

    

    
}

#if compiler(>=6)
extension HttpTraceSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpTraceSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpTraceSummary {
        return
            try HttpTraceSummary(
                method: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                status: FfiConverterOptionUInt16.read(from: &buf), 
                bytes: FfiConverterUInt64.read(from: &buf), 
                elapsedMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HttpTraceSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.method, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterOptionUInt16.write(value.status, into: &buf)
        FfiConverterUInt64.write(value.bytes, into: &buf)
        FfiConverterUInt64.write(value.elapsedMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpTraceSummary_lift(_ buf: RustBuffer) throws -> HttpTraceSummary {
    return try FfiConverterTypeHttpTraceSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpTraceSummary_lower(_ value: HttpTraceSummary) -> RustBuffer {
    return FfiConverterTypeHttpTraceSummary.lower(value)
}


/**
 * A prepared stream session as reported to the player: the opaque
 * handle plus metadata. The signed URL never crosses this boundary.
 */
public struct PreparedStream: Equatable, Hashable {
    /**
     * Opaque session handle for `stream_open`/`stream_read`/...
     */
    public var handle: String
    /**
     * MIME type; pinned across re-mints.
     */
    public var mime: String
    /**
     * Format itag when reported.
     */
    public var itag: UInt32?
    /**
     * Bitrate hint in kbps.
     */
    public var bitrateKbps: UInt32?
    /**
     * Reported length in bytes, when known.
     */
    public var contentLength: UInt64?
    /**
     * URL expiry, epoch ms.
     */
    public var expiresAtMs: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque session handle for `stream_open`/`stream_read`/...
         */handle: String, 
        /**
         * MIME type; pinned across re-mints.
         */mime: String, 
        /**
         * Format itag when reported.
         */itag: UInt32?, 
        /**
         * Bitrate hint in kbps.
         */bitrateKbps: UInt32?, 
        /**
         * Reported length in bytes, when known.
         */contentLength: UInt64?, 
        /**
         * URL expiry, epoch ms.
         */expiresAtMs: UInt64?) {
        self.handle = handle
        self.mime = mime
        self.itag = itag
        self.bitrateKbps = bitrateKbps
        self.contentLength = contentLength
        self.expiresAtMs = expiresAtMs
    }

    

    
}

#if compiler(>=6)
extension PreparedStream: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreparedStream: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreparedStream {
        return
            try PreparedStream(
                handle: FfiConverterString.read(from: &buf), 
                mime: FfiConverterString.read(from: &buf), 
                itag: FfiConverterOptionUInt32.read(from: &buf), 
                bitrateKbps: FfiConverterOptionUInt32.read(from: &buf), 
                contentLength: FfiConverterOptionUInt64.read(from: &buf), 
                expiresAtMs: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PreparedStream, into buf: inout [UInt8]) {
        FfiConverterString.write(value.handle, into: &buf)
        FfiConverterString.write(value.mime, into: &buf)
        FfiConverterOptionUInt32.write(value.itag, into: &buf)
        FfiConverterOptionUInt32.write(value.bitrateKbps, into: &buf)
        FfiConverterOptionUInt64.write(value.contentLength, into: &buf)
        FfiConverterOptionUInt64.write(value.expiresAtMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedStream_lift(_ buf: RustBuffer) throws -> PreparedStream {
    return try FfiConverterTypePreparedStream.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedStream_lower(_ value: PreparedStream) -> RustBuffer {
    return FfiConverterTypePreparedStream.lower(value)
}


/**
 * A resolved stream. `url` is signed — never log it.
 */
public struct ResolvedResource: Equatable, Hashable {
    /**
     * Direct stream URL (signed; redact everywhere).
     */
    public var url: String
    /**
     * MIME type, e.g. `audio/mp4`.
     */
    public var mime: String
    /**
     * Bitrate in kbps when the guest reported one.
     */
    public var bitrateKbps: UInt32?
    /**
     * `expire=` converted to epoch milliseconds.
     */
    public var expiresAtMs: UInt64?
    /**
     * Ladder rung that produced the URL.
     */
    public var client: String
    /**
     * Reported `contentLength` of the picked format in bytes.
     */
    public var contentLength: UInt64?
    /**
     * Provider format itag when the guest reported one.
     */
    public var itag: UInt32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Direct stream URL (signed; redact everywhere).
         */url: String, 
        /**
         * MIME type, e.g. `audio/mp4`.
         */mime: String, 
        /**
         * Bitrate in kbps when the guest reported one.
         */bitrateKbps: UInt32?, 
        /**
         * `expire=` converted to epoch milliseconds.
         */expiresAtMs: UInt64?, 
        /**
         * Ladder rung that produced the URL.
         */client: String, 
        /**
         * Reported `contentLength` of the picked format in bytes.
         */contentLength: UInt64?, 
        /**
         * Provider format itag when the guest reported one.
         */itag: UInt32?) {
        self.url = url
        self.mime = mime
        self.bitrateKbps = bitrateKbps
        self.expiresAtMs = expiresAtMs
        self.client = client
        self.contentLength = contentLength
        self.itag = itag
    }

    

    
}

#if compiler(>=6)
extension ResolvedResource: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeResolvedResource: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResolvedResource {
        return
            try ResolvedResource(
                url: FfiConverterString.read(from: &buf), 
                mime: FfiConverterString.read(from: &buf), 
                bitrateKbps: FfiConverterOptionUInt32.read(from: &buf), 
                expiresAtMs: FfiConverterOptionUInt64.read(from: &buf), 
                client: FfiConverterString.read(from: &buf), 
                contentLength: FfiConverterOptionUInt64.read(from: &buf), 
                itag: FfiConverterOptionUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ResolvedResource, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.mime, into: &buf)
        FfiConverterOptionUInt32.write(value.bitrateKbps, into: &buf)
        FfiConverterOptionUInt64.write(value.expiresAtMs, into: &buf)
        FfiConverterString.write(value.client, into: &buf)
        FfiConverterOptionUInt64.write(value.contentLength, into: &buf)
        FfiConverterOptionUInt32.write(value.itag, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResolvedResource_lift(_ buf: RustBuffer) throws -> ResolvedResource {
    return try FfiConverterTypeResolvedResource.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResolvedResource_lower(_ value: ResolvedResource) -> RustBuffer {
    return FfiConverterTypeResolvedResource.lower(value)
}


/**
 * Result of the fuel-gate measurement (spin conformance guest).
 */
public struct SpinReport: Equatable, Hashable {
    /**
     * Wall-clock time until the trap.
     */
    public var elapsedMs: UInt64
    /**
     * Fuel consumed before the trap.
     */
    public var fuelUsed: UInt64
    /**
     * Terminal error kind (`budget-exceeded` expected).
     */
    public var kind: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Wall-clock time until the trap.
         */elapsedMs: UInt64, 
        /**
         * Fuel consumed before the trap.
         */fuelUsed: UInt64, 
        /**
         * Terminal error kind (`budget-exceeded` expected).
         */kind: String) {
        self.elapsedMs = elapsedMs
        self.fuelUsed = fuelUsed
        self.kind = kind
    }

    

    
}

#if compiler(>=6)
extension SpinReport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpinReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpinReport {
        return
            try SpinReport(
                elapsedMs: FfiConverterUInt64.read(from: &buf), 
                fuelUsed: FfiConverterUInt64.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SpinReport, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.elapsedMs, into: &buf)
        FfiConverterUInt64.write(value.fuelUsed, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpinReport_lift(_ buf: RustBuffer) throws -> SpinReport {
    return try FfiConverterTypeSpinReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpinReport_lower(_ value: SpinReport) -> RustBuffer {
    return FfiConverterTypeSpinReport.lower(value)
}


/**
 * Lifecycle marks for one stream session: epoch-ms timestamps plus
 * durations, for joining intent → prepared → attached → rendered.
 */
public struct StreamPhaseMarks: Equatable, Hashable {
    /**
     * Epoch ms when `prepare` registered the session.
     */
    public var prepareStartedMs: UInt64
    /**
     * Duration of the minting `playback.resolve`, when known.
     */
    public var resolveMs: UInt64?
    /**
     * Duration of the most recent re-mint, when one ran.
     */
    public var mintMs: UInt64?
    /**
     * Epoch ms when the first byte landed.
     */
    public var firstByteMs: UInt64?
    /**
     * Epoch ms when the head-fill bound was covered.
     */
    public var headReadyMs: UInt64?
    /**
     * Epoch ms of the first attach.
     */
    public var attachMs: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Epoch ms when `prepare` registered the session.
         */prepareStartedMs: UInt64, 
        /**
         * Duration of the minting `playback.resolve`, when known.
         */resolveMs: UInt64?, 
        /**
         * Duration of the most recent re-mint, when one ran.
         */mintMs: UInt64?, 
        /**
         * Epoch ms when the first byte landed.
         */firstByteMs: UInt64?, 
        /**
         * Epoch ms when the head-fill bound was covered.
         */headReadyMs: UInt64?, 
        /**
         * Epoch ms of the first attach.
         */attachMs: UInt64?) {
        self.prepareStartedMs = prepareStartedMs
        self.resolveMs = resolveMs
        self.mintMs = mintMs
        self.firstByteMs = firstByteMs
        self.headReadyMs = headReadyMs
        self.attachMs = attachMs
    }

    

    
}

#if compiler(>=6)
extension StreamPhaseMarks: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamPhaseMarks: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamPhaseMarks {
        return
            try StreamPhaseMarks(
                prepareStartedMs: FfiConverterUInt64.read(from: &buf), 
                resolveMs: FfiConverterOptionUInt64.read(from: &buf), 
                mintMs: FfiConverterOptionUInt64.read(from: &buf), 
                firstByteMs: FfiConverterOptionUInt64.read(from: &buf), 
                headReadyMs: FfiConverterOptionUInt64.read(from: &buf), 
                attachMs: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: StreamPhaseMarks, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.prepareStartedMs, into: &buf)
        FfiConverterOptionUInt64.write(value.resolveMs, into: &buf)
        FfiConverterOptionUInt64.write(value.mintMs, into: &buf)
        FfiConverterOptionUInt64.write(value.firstByteMs, into: &buf)
        FfiConverterOptionUInt64.write(value.headReadyMs, into: &buf)
        FfiConverterOptionUInt64.write(value.attachMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamPhaseMarks_lift(_ buf: RustBuffer) throws -> StreamPhaseMarks {
    return try FfiConverterTypeStreamPhaseMarks.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamPhaseMarks_lower(_ value: StreamPhaseMarks) -> RustBuffer {
    return FfiConverterTypeStreamPhaseMarks.lower(value)
}


/**
 * Errors raised synchronously by [`PluginHost`] calls.
 *
 * Field names avoid `message`: in the Kotlin binding an exception
 * property named `message` collides with `Throwable.message`.
 */
public 
enum HostError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Artifact or manifest rejected at load.
     */
    case Load(
        /**
         * Rejection detail.
         */detail: String
    )
    /**
     * `start_resolve`/`cancel` referenced an id that is not loaded.
     */
    case UnknownPlugin(
        /**
         * The missing plugin id.
         */id: String
    )
    /**
     * Internal runtime failure.
     */
    case Runtime(
        /**
         * Detail.
         */detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension HostError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostError: FfiConverterRustBuffer {
    typealias SwiftType = HostError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Load(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 2: return .UnknownPlugin(
            id: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Runtime(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HostError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Load(detail):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .UnknownPlugin(id):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .Runtime(detail):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostError_lift(_ buf: RustBuffer) throws -> HostError {
    return try FfiConverterTypeHostError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostError_lower(_ value: HostError) -> RustBuffer {
    return FfiConverterTypeHostError.lower(value)
}


/**
 * Terminal outcome of one `start_prepare` invocation.
 */

public enum PrepareOutcome: Equatable, Hashable {
    
    /**
     * The resolve produced a source and the seam registered it.
     */
    case prepared(
        /**
         * The prepared session handle + metadata.
         */stream: PreparedStream, 
        /**
         * Handles this prepare superseded or pruned — the caller's
         * handle routing must drop these so a dead session's entry
         * can never serve a later attach.
         */superseded: [String], 
        /**
         * Invocation accounting for the resolve.
         */attempt: AttemptSummary
    )
    /**
     * The resolve or the seam registration failed.
     */
    case failed(
        /**
         * Taxonomy kind (`no-result`, `cancelled`, ...).
         */kind: String, 
        /**
         * Human-readable detail (never contains the URL).
         */message: String, 
        /**
         * Invocation accounting for the resolve.
         */attempt: AttemptSummary
    )





}

#if compiler(>=6)
extension PrepareOutcome: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrepareOutcome: FfiConverterRustBuffer {
    typealias SwiftType = PrepareOutcome

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrepareOutcome {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .prepared(stream: try FfiConverterTypePreparedStream.read(from: &buf), superseded: try FfiConverterSequenceString.read(from: &buf), attempt: try FfiConverterTypeAttemptSummary.read(from: &buf)
        )
        
        case 2: return .failed(kind: try FfiConverterString.read(from: &buf), message: try FfiConverterString.read(from: &buf), attempt: try FfiConverterTypeAttemptSummary.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PrepareOutcome, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .prepared(stream,superseded,attempt):
            writeInt(&buf, Int32(1))
            FfiConverterTypePreparedStream.write(stream, into: &buf)
            FfiConverterSequenceString.write(superseded, into: &buf)
            FfiConverterTypeAttemptSummary.write(attempt, into: &buf)
            
        
        case let .failed(kind,message,attempt):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(kind, into: &buf)
            FfiConverterString.write(message, into: &buf)
            FfiConverterTypeAttemptSummary.write(attempt, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrepareOutcome_lift(_ buf: RustBuffer) throws -> PrepareOutcome {
    return try FfiConverterTypePrepareOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrepareOutcome_lower(_ value: PrepareOutcome) -> RustBuffer {
    return FfiConverterTypePrepareOutcome.lower(value)
}



/**
 * Terminal outcome of one `start_request` invocation. The result is
 * raw JSON — the typed [`ResolveOutcome`] remains for resolve callers.
 */

public enum RequestOutcome: Equatable, Hashable {
    
    /**
     * The invocation produced a `done` result.
     */
    case succeeded(
        /**
         * `done.result` serialized to JSON.
         */resultJson: String, 
        /**
         * Invocation accounting.
         */attempt: AttemptSummary
    )
    /**
     * The invocation failed; `kind` is the ABI error taxonomy.
     */
    case failed(
        /**
         * Taxonomy kind.
         */kind: String, 
        /**
         * Human-readable detail (never contains signed URLs).
         */message: String, 
        /**
         * Invocation accounting.
         */attempt: AttemptSummary
    )





}

#if compiler(>=6)
extension RequestOutcome: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRequestOutcome: FfiConverterRustBuffer {
    typealias SwiftType = RequestOutcome

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RequestOutcome {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .succeeded(resultJson: try FfiConverterString.read(from: &buf), attempt: try FfiConverterTypeAttemptSummary.read(from: &buf)
        )
        
        case 2: return .failed(kind: try FfiConverterString.read(from: &buf), message: try FfiConverterString.read(from: &buf), attempt: try FfiConverterTypeAttemptSummary.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RequestOutcome, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .succeeded(resultJson,attempt):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(resultJson, into: &buf)
            FfiConverterTypeAttemptSummary.write(attempt, into: &buf)
            
        
        case let .failed(kind,message,attempt):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(kind, into: &buf)
            FfiConverterString.write(message, into: &buf)
            FfiConverterTypeAttemptSummary.write(attempt, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRequestOutcome_lift(_ buf: RustBuffer) throws -> RequestOutcome {
    return try FfiConverterTypeRequestOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRequestOutcome_lower(_ value: RequestOutcome) -> RustBuffer {
    return FfiConverterTypeRequestOutcome.lower(value)
}



/**
 * Terminal outcome of one `start_resolve` invocation.
 */

public enum ResolveOutcome: Equatable, Hashable {
    
    /**
     * A plain audio URL was produced.
     */
    case resolved(
        /**
         * The stream.
         */resource: ResolvedResource, 
        /**
         * Invocation accounting.
         */attempt: AttemptSummary
    )
    /**
     * The invocation failed; `kind` is the ABI error taxonomy.
     */
    case failed(
        /**
         * Taxonomy kind (`no-result`, `cancelled`, ...).
         */kind: String, 
        /**
         * Human-readable detail (never contains the URL).
         */message: String, 
        /**
         * Invocation accounting.
         */attempt: AttemptSummary
    )





}

#if compiler(>=6)
extension ResolveOutcome: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeResolveOutcome: FfiConverterRustBuffer {
    typealias SwiftType = ResolveOutcome

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResolveOutcome {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .resolved(resource: try FfiConverterTypeResolvedResource.read(from: &buf), attempt: try FfiConverterTypeAttemptSummary.read(from: &buf)
        )
        
        case 2: return .failed(kind: try FfiConverterString.read(from: &buf), message: try FfiConverterString.read(from: &buf), attempt: try FfiConverterTypeAttemptSummary.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ResolveOutcome, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .resolved(resource,attempt):
            writeInt(&buf, Int32(1))
            FfiConverterTypeResolvedResource.write(resource, into: &buf)
            FfiConverterTypeAttemptSummary.write(attempt, into: &buf)
            
        
        case let .failed(kind,message,attempt):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(kind, into: &buf)
            FfiConverterString.write(message, into: &buf)
            FfiConverterTypeAttemptSummary.write(attempt, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResolveOutcome_lift(_ buf: RustBuffer) throws -> ResolveOutcome {
    return try FfiConverterTypeResolveOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResolveOutcome_lower(_ value: ResolveOutcome) -> RustBuffer {
    return FfiConverterTypeResolveOutcome.lower(value)
}



/**
 * Errors raised synchronously by the `stream_*` calls.
 *
 * Field names avoid `message` for the same reason as [`HostError`].
 */
public 
enum StreamError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * `HostConfig.stream_path` was unset — the seam is not running.
     */
    case Unavailable
    /**
     * The session operation failed; `kind` is the ABI taxonomy.
     */
    case Failed(
        /**
         * Kebab-case error kind.
         */kind: String, 
        /**
         * Failure detail (never contains the signed URL).
         */detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension StreamError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamError: FfiConverterRustBuffer {
    typealias SwiftType = StreamError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Unavailable
        case 2: return .Failed(
            kind: try FfiConverterString.read(from: &buf), 
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StreamError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .Unavailable:
            writeInt(&buf, Int32(1))
        
        
        case let .Failed(kind,detail):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(kind, into: &buf)
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamError_lift(_ buf: RustBuffer) throws -> StreamError {
    return try FfiConverterTypeStreamError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamError_lower(_ value: StreamError) -> RustBuffer {
    return FfiConverterTypeStreamError.lower(value)
}




/**
 * Receives the terminal outcome of [`PluginHost::start_prepare`].
 */
public protocol PrepareListener: AnyObject, Sendable {
    
    /**
     * Called exactly once per request, on a runtime worker thread.
     */
    func onOutcome(requestId: String, outcome: PrepareOutcome) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfacePrepareListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfacePrepareListener = UniffiVTableCallbackInterfacePrepareListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfacePrepareListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface PrepareListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfacePrepareListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface PrepareListener: handle missing in uniffiClone")
            }
        },
        onOutcome: { (
            uniffiHandle: UInt64,
            requestId: RustBuffer,
            outcome: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfacePrepareListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onOutcome(
                     requestId: try FfiConverterString.lift(requestId),
                     outcome: try FfiConverterTypePrepareOutcome_lift(outcome)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfacePrepareListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfacePrepareListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitPrepareListener() {
    uniffi_auqw_mobile_bindings_fn_init_callback_vtable_preparelistener(UniffiCallbackInterfacePrepareListener.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfacePrepareListener {
    fileprivate static let handleMap = UniffiHandleMap<PrepareListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfacePrepareListener : FfiConverter {
    typealias SwiftType = PrepareListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfacePrepareListener_lift(_ handle: UInt64) throws -> PrepareListener {
    return try FfiConverterCallbackInterfacePrepareListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfacePrepareListener_lower(_ v: PrepareListener) -> UInt64 {
    return FfiConverterCallbackInterfacePrepareListener.lower(v)
}




/**
 * Receives the terminal outcome of an invocation started with
 * [`PluginHost::start_request`].
 */
public protocol RequestListener: AnyObject, Sendable {
    
    /**
     * Called exactly once per request, on a runtime worker thread.
     */
    func onOutcome(requestId: String, outcome: RequestOutcome) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceRequestListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceRequestListener = UniffiVTableCallbackInterfaceRequestListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceRequestListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface RequestListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceRequestListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface RequestListener: handle missing in uniffiClone")
            }
        },
        onOutcome: { (
            uniffiHandle: UInt64,
            requestId: RustBuffer,
            outcome: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceRequestListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onOutcome(
                     requestId: try FfiConverterString.lift(requestId),
                     outcome: try FfiConverterTypeRequestOutcome_lift(outcome)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceRequestListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceRequestListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitRequestListener() {
    uniffi_auqw_mobile_bindings_fn_init_callback_vtable_requestlistener(UniffiCallbackInterfaceRequestListener.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceRequestListener {
    fileprivate static let handleMap = UniffiHandleMap<RequestListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceRequestListener : FfiConverter {
    typealias SwiftType = RequestListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceRequestListener_lift(_ handle: UInt64) throws -> RequestListener {
    return try FfiConverterCallbackInterfaceRequestListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceRequestListener_lower(_ v: RequestListener) -> UInt64 {
    return FfiConverterCallbackInterfaceRequestListener.lower(v)
}




/**
 * Receives the terminal outcome of an invocation started with
 * [`PluginHost::start_resolve`].
 */
public protocol ResolveListener: AnyObject, Sendable {
    
    /**
     * Called exactly once per request, on a runtime worker thread.
     */
    func onOutcome(requestId: String, outcome: ResolveOutcome) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceResolveListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceResolveListener = UniffiVTableCallbackInterfaceResolveListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceResolveListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ResolveListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceResolveListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ResolveListener: handle missing in uniffiClone")
            }
        },
        onOutcome: { (
            uniffiHandle: UInt64,
            requestId: RustBuffer,
            outcome: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceResolveListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onOutcome(
                     requestId: try FfiConverterString.lift(requestId),
                     outcome: try FfiConverterTypeResolveOutcome_lift(outcome)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceResolveListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceResolveListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitResolveListener() {
    uniffi_auqw_mobile_bindings_fn_init_callback_vtable_resolvelistener(UniffiCallbackInterfaceResolveListener.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceResolveListener {
    fileprivate static let handleMap = UniffiHandleMap<ResolveListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceResolveListener : FfiConverter {
    typealias SwiftType = ResolveListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceResolveListener_lift(_ handle: UInt64) throws -> ResolveListener {
    return try FfiConverterCallbackInterfaceResolveListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceResolveListener_lower(_ v: ResolveListener) -> UInt64 {
    return FfiConverterCallbackInterfaceResolveListener.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGuestLogSummary: FfiConverterRustBuffer {
    typealias SwiftType = [GuestLogSummary]

    public static func write(_ value: [GuestLogSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGuestLogSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GuestLogSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [GuestLogSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGuestLogSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHttpTraceSummary: FfiConverterRustBuffer {
    typealias SwiftType = [HttpTraceSummary]

    public static func write(_ value: [HttpTraceSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHttpTraceSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HttpTraceSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [HttpTraceSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHttpTraceSummary.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_auqw_mobile_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_cancel() != 26661) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_load_plugin() != 41359) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_run_spin() != 34269) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_start_request() != 7187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_start_resolve() != 51654) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_start_prepare() != 57130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_stream_close() != 22132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_stream_open() != 39188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_stream_phase_marks() != 17009) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_stream_read() != 33146) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_pluginhost_stream_release() != 34455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_constructor_pluginhost_new() != 45559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_requestlistener_on_outcome() != 46008) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_resolvelistener_on_outcome() != 25209) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_auqw_mobile_bindings_checksum_method_preparelistener_on_outcome() != 64282) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitPrepareListener()
    uniffiCallbackInitRequestListener()
    uniffiCallbackInitResolveListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAuqwMobileBindingsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all