import { run as runErrors } from './errors.test.ts';
import { run as runCancellation } from './cancellation.test.ts';
import { run as runDomain } from './domain.test.ts';
import { run as runRetry } from './retry.test.ts';
import { run as runLikes } from './library/likes.test.ts';
import { run as runLibrary } from './library/library.test.ts';
import { run as runPlaylists } from './library/playlists.test.ts';
import { run as runHistory } from './library/history.test.ts';
import { run as runLyrics } from './library/lyrics.test.ts';
import { run as runExportImport } from './library/export-import.test.ts';
import { run as runArtworkCache } from './library/artwork-cache.test.ts';
import { run as runCorrections } from './library/corrections.test.ts';
import { run as runQueue } from './queue/queue-engine.test.ts';
import { run as runRadioTail } from './queue/radio-tail.test.ts';
import { run as runMatching } from './matching/matching-engine.test.ts';
import { run as runSearch } from './search/search-session.test.ts';
import { run as runFakes } from './testing/fakes.test.ts';
import { run as runSession } from './session/session.test.ts';
import { run as runHlc } from './sync/hlc.test.ts';
import { run as runSyncEngine } from './sync/sync-engine.test.ts';
import { run as runSyncClient } from './sync/sync-client.test.ts';
import { run as runSyncScheduler } from './sync/sync-scheduler.test.ts';
import { run as runSyncHost } from './sync/sync-host.test.ts';
import { run as runSyncProjection } from './sync/sync-projection.test.ts';
import { run as runDownloadManager } from './downloads/download-manager.test.ts';
import { run as runProviderRouter } from './providers/provider-router.test.ts';
import { run as runLocalSource } from './local/local-source.test.ts';
import { run as runTransferPolicy } from './downloads/transfer-policy.test.ts';

runErrors();
runCancellation();
runDomain();
await runRetry();
runLikes();
runLibrary();
runPlaylists();
runHistory();
await runExportImport();
await runArtworkCache();
await runCorrections();
await runLyrics();
runQueue();
await runRadioTail();
runMatching();
await runSearch();
await runFakes();
await runSession();
runHlc();
await runSyncEngine();
await runSyncClient();
await runSyncScheduler();
await runSyncHost();
await runSyncProjection();
await runDownloadManager();
await runProviderRouter();
await runLocalSource();
await runTransferPolicy();
