#!/usr/bin/env node
// Generates the guest errorKind vocabulary from the contract schema.
// `sdk/contract/messages.schema.json` $defs.errorKind is the single
// source; this splices the same list into every hand-written Rust
// allowlist so a new kind ships with one edit, not two. `--check`
// verifies without writing (CI drift gate).
//
//   node tooling/gen-kinds.mjs [--check]

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = join(fileURLToPath(import.meta.url), '../..');
const check = process.argv.includes('--check');

const schema = JSON.parse(
  readFileSync(join(ROOT, 'sdk/contract/messages.schema.json'), 'utf8'),
);
const kinds = schema?.$defs?.errorKind?.enum;
if (
  !Array.isArray(kinds) ||
  kinds.length === 0 ||
  kinds.some((k) => typeof k !== 'string' || !/^[a-z-]+$/.test(k))
) {
  throw new Error('messages.schema.json: $defs.errorKind.enum unreadable');
}
const body = kinds.map((k) => `    "${k}",\n`).join('');
const generated =
  `    // GENERATED by tooling/gen-kinds.mjs from messages.schema.json —\n` +
  `    // do not hand-edit, the enum in the schema is the source.\n`;

// [file, const-name] pairs — every guest-facing kind allowlist lives here.
const targets = [
  ['crates/plugin-host/src/error.rs', 'GUEST_FAIL_KINDS'],
  ['sdk/rust/src/lib.rs', 'ERROR_KINDS'],
];

let dirty = false;
for (const [file, name] of targets) {
  const path = join(ROOT, file);
  const text = readFileSync(path, 'utf8');
  const re = new RegExp(
    `(const ${name}: &\\[&str\\] = &\\[)([^]*?)(\\];)`,
  );
  const m = re.exec(text);
  if (!m) {
    throw new Error(`${file}: const ${name} not found`);
  }
  const replacement = `${m[1]}\n${generated}${body}${m[3]}`;
  if (m[0] !== replacement) {
    if (check) {
      console.error(`gen-kinds: ${file} ${name} drifted from the schema`);
      dirty = true;
    } else {
      writeFileSync(path, text.replace(re, replacement));
      console.log(`gen-kinds: rewrote ${file} ${name}`);
    }
  }
}
if (dirty) {
  process.exit(1);
}
if (!check) {
  console.log('gen-kinds: all kind lists match the schema');
}
